src/Entity/Knife.php
<?php

namespace App\Entity;

use App\Repository\KnifeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KnifeRepository::class)
 */
class Knife
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $maker;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $blade_length;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $blade_thickness;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $blade_material;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $total_length;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $handle_length;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $handle_material;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="knives")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Location::class, inversedBy="knife")
     */
    private $location;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="knife", orphanRemoval=true)
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMaker(): ?string
    {
        return $this->maker;
    }

    public function setMaker(string $maker): self
    {
        $this->maker = $maker;

        return $this;
    }

    public function getBladeLength(): ?float
    {
        return $this->blade_length;
    }

    public function setBladeLength(?float $blade_length): self
    {
        $this->blade_length = $blade_length;

        return $this;
    }

    public function getBladeThickness(): ?float
    {
        return $this->blade_thickness;
    }

    public function setBladeThickness(?float $blade_thickness): self
    {
        $this->blade_thickness = $blade_thickness;

        return $this;
    }

    public function getBladeMaterial(): ?string
    {
        return $this->blade_material;
    }

    public function setBladeMaterial(?string $blade_material): self
    {
        $this->blade_material = $blade_material;

        return $this;
    }

    public function getTotalLength(): ?float
    {
        return $this->total_length;
    }

    public function setTotalLength(?float $total_length): self
    {
        $this->total_length = $total_length;

        return $this;
    }

    public function getHandleLength(): ?float
    {
        return $this->handle_length;
    }

    public function setHandleLength(?float $handle_length): self
    {
        $this->handle_length = $handle_length;

        return $this;
    }

    public function getHandleMaterial(): ?string
    {
        return $this->handle_material;
    }

    public function setHandleMaterial(?string $handle_material): self
    {
        $this->handle_material = $handle_material;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setKnife($this);
        }
        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getKnife() === $this) {
                $image->setKnife(null);
            }
        }
        return $this;
    }
}

src/Form/KnifeType.php
<?php

namespace App\Form;

use App\Entity\Image;
use App\Entity\Knife;
use App\Entity\User;
use PhpParser\Parser\Multiple;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Security\Core\Security;

class KnifeType extends AbstractType
{   
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom'
            ])
            ->add('maker', TextType::class, [
                'label' => 'Fabricant'
            ])
            ->add('blade_length', NumberType::class, [
                'required' => false,
                'label' => 'Longueur de la lame'
            ])
            ->add('blade_thickness', NumberType::class, [
                'required' => false,
                'label' => 'Epaisseur de la lame'
            ])
            ->add('blade_material', TextType::class, [
                'required' => false,
                'label' => 'Matériau de la lame'
            ])
            ->add('handle_length', NumberType::class, [
                'required' => false,
                'label' => 'Longueur du manche'
            ])
            ->add('handle_material', TextType::class, [
                'required' => false,
                'label' => 'Matéreiau du manche'
            ])
            ->add('total_length', NumberType::class, [
                'required' => false,
                'label' => 'Longueur totale'
            ])
            ->add('state', ChoiceType::class, [
                'choices' => [
                'En ma possession' => 'En ma possession',
                'Revendu' => 'Revendu',
                'Perdu' => 'Perdu',
                'label' => 'Etat'
                ]])
            ->add('user', EntityType::class, [
                'class' => User::class, 
                'choice_label' => 'lastname',
                'multiple' => false,
                'expanded' => false,
                'label' => 'Utilisateur'
            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Knife::class,
        ]);
    }
}

src/Controller/KnifeController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Knife;
use App\Entity\User;
use App\Form\KnifeType;
use App\Repository\KnifeRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @Route("/knife")
 */
class KnifeController extends AbstractController
{
    /**
     * @Route("/", name="knife_index", methods={"GET", "POST"})
     */
    public function index(KnifeRepository $knifeRepository): Response
    {
        return $this->render('knife/index.html.twig', [
            'knives' => $knifeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="knife_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $knife = new Knife();
        $form = $this->createForm(KnifeType::class, $knife);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($knife);
            $entityManager->flush();

            return $this->redirectToRoute('image_new');
        }

        return $this->render('knife/new.html.twig', [
            'knife' => $knife,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="knife_show", methods={"GET", "POST"})
     */
    public function show(Knife $knife): Response
    {
        return $this->render('knife/show.html.twig', [
            'knife' => $knife,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="knife_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Knife $knife): Response
    {
        $form = $this->createForm(KnifeType::class, $knife);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('knife_index');
        }

        return $this->render('knife/edit.html.twig', [
            'knife' => $knife,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="knife_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Knife $knife, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$knife->getId(), $request->request->get('_token'))) {
            $entityManager->remove($knife);
            $entityManager->flush();
        }

        return $this->redirectToRoute('knife_index');
    }
}

templates/knife/_delete_form.html.twig
<form method="post" action="{{ path('knife_delete', {'id': knife.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ knife.id) }}">
    <button class="btn">Delete</button>
</form>

templates/knife/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/knife/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un couteau{% endblock %}

{% block body %}
    <h1>Modifier un couteau</h1>

    {{ include('knife/_form.html.twig', {'button_label': 'Update'}) }}

    <div>
        <p>sur une image pour la modifier :</p> 
        {% for image in knife.images %}
        <a href="{{ path('image_edit', {'id' : image.id}) }}"> <img class="image_edit" src="{{ vich_uploader_asset(image, 'posterFile') }}" alt=""><br></a>
        {% endfor %}
    </div>
    {{ include('knife/_delete_form.html.twig') }}
    <div>
        <a class="btn" href="{{ path('knife_index') }}">back to list</a>
    </div>
{% endblock %}

templates/knife/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Knife index{% endblock %}

{% block body %}
    <h1>Index des couteaux</h1>
<div>
    <table class="table_all">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Fabricant</th>
                <th>Etat</th>
                <th>Propriétaire</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for knife in knives %}
            <tr>
                <td>{{ knife.name }}</td>
                <td>
                   {{ knife.maker }}
                </td>
                <td>{{ knife.state }}</td>
                <td>{{ knife.user.firstname }}</td>
                <td>
                    <a href="{{ path('knife_show', {'id': knife.id}) }}">Voir détails</a>
                    <a href="{{ path('knife_edit', {'id': knife.id}) }}">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="create">
    <a class="btn" href="{{ path('knife_new') }}">Create new</a>
</div>
{% endblock %}

templates/knife/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Knife{% endblock %}

{% block body %}
    <h1>Ajouter un couteau</h1>

    {{ include('knife/_form.html.twig') }}

    <a href="{{ path('knife_index') }}">back to list</a>
{% endblock %}

templates/knife/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Knife{% endblock %}

{% block body %}
    <div class="full_name">
        <h1 class="knife_name">{{ knife.name }}</h1> par <h2 class="knife_maker">{{ knife.maker }}</h2>
    </div>
    <table class="table_details">
        <tbody>
            <tr>
                <th>Longeur de lame</th>
                <td>{{ knife.bladeLength }} mm</td>
            </tr>
            <tr>
                <th>Epaisseur de lame</th>
                <td>{{ knife.bladeThickness }} mm</td>
            </tr>
            <tr>
                <th>Materiau de la lame</th>
                <td>{{ knife.bladeMaterial }}</td>
            </tr>
            <tr>
                <th>Longueur du manche</th>
                <td>{{ knife.handleLength }} mm</td>
            </tr>
            <tr>
                <th>Materiau du manche</th>
                <td>{{ knife.handleMaterial }}</td>
            </tr>
            <tr>
                <th>Longueur totale</th>
                <td>{{ knife.totalLength }} mm</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ knife.state }}</td>
            </tr>
        </tbody>
    </table>
    <div class="images">
        {% for image in knife.images %}
        <img src="{{ vich_uploader_asset(image, 'posterFile') }}">
        {% endfor %}
    </div>
    <div>
        <a class="btn" href="{{ path('knife_index') }}">back to list</a>

        <a class="btn" href="{{ path('knife_edit', {'id': knife.id}) }}">edit</a>
    </div>
    {{ include('knife/_delete_form.html.twig') }}
{% endblock %}